import { z } from 'zod';
import { sendOpenRouterSpeech } from '@/shared/api/openrouter';
import { DEFAULT_SPEECH_MODEL } from '@/shared/api/openrouter-models';
import { getOpenRouterSpeechCapabilities, getOpenRouterSpeechResponseFormat, getSafeSpeechResponseFormat, getSafeSpeechVoice } from '@/shared/api/openrouter-speech-capabilities';
import { readBoundedBytes } from '@/shared/media/bounded-bytes';
import { wrapSpeechPcmAsWav } from '@/shared/media/speech-wave';
import { EMPTY_PROVIDER_USAGE, type ProviderAdapter } from '../contracts/provider-contracts';
import { ProviderAdapterError } from '../core/provider-errors';

export const speechOptionsSchema = z.object({
  inputText: z.string().trim().min(1).max(5000),
  language: z.enum(['auto', 'ru', 'en', 'de', 'es', 'zh']).default('auto'),
  model: z.string().min(1).max(200).default(DEFAULT_SPEECH_MODEL),
  responseFormat: z.enum(['mp3', 'pcm']).default('mp3'),
  seed: z.number().int().optional(), speed: z.number().min(0.25).max(4).optional(),
  temperature: z.number().min(0).max(2).optional(), topP: z.number().min(0).max(1).optional(),
  voice: z.string().min(1).max(100).default('Eve'),
});
export type SpeechOptions = z.infer<typeof speechOptionsSchema>;
export interface SpeechResult { audioBody: Uint8Array; contentType: string; generationId: string | null }
const MAX_SPEECH_BYTES = 20 * 1024 * 1024; // Base64 checkpoint stays below the existing 32 MiB envelope.
const speechCheckpointSchema = z.object({
  audioBase64: z.string().max(Math.ceil(MAX_SPEECH_BYTES / 3) * 4 + 64),
  contentType: z.string(), generationId: z.string().nullable(),
});

export function createSpeechProviderCall(options: SpeechOptions, outerSignal: AbortSignal, requestSpeech = sendOpenRouterSpeech) {
  const input = speechOptionsSchema.parse(options);
  if (input.model === 'microsoft/mai-voice-2' && input.inputText.length < 10) {
    throw new ProviderAdapterError({ classification: 'permanent', code: 'invalid_request', httpStatus: 400,
      message: 'MAI-Voice-2 needs a full sentence (at least 10 characters).', providerOperationId: null, retryAfterMs: null });
  }
  const capabilities = getOpenRouterSpeechCapabilities(input.model);
  const responseFormat = getOpenRouterSpeechResponseFormat(input.model, getSafeSpeechResponseFormat(input.model, input.responseFormat));
  return {
    modelId: input.model,
    operation: 'generate_speech',
    checkpoint: {
      serialize(result: SpeechResult) {
        return { audioBase64: Buffer.from(result.audioBody).toString('base64'), contentType: result.contentType, generationId: result.generationId };
      },
      deserialize(value: unknown): SpeechResult {
        const saved = speechCheckpointSchema.parse(value);
        return { audioBody: new Uint8Array(Buffer.from(saved.audioBase64, 'base64')), contentType: saved.contentType, generationId: saved.generationId };
      },
    },
    async invoke({ adapter, apiKey }: { adapter: ProviderAdapter; apiKey: string }) {
      const signal = AbortSignal.any([outerSignal, AbortSignal.timeout(180_000)]);
      const response = await requestSpeech({
        apiKey, input: input.inputText, model: input.model, responseFormat, signal,
        seed: capabilities.supportsSeed ? input.seed : undefined,
        speed: capabilities.supportsSpeed ? input.speed : undefined,
        temperature: capabilities.supportsTemperature ? input.temperature : undefined,
        topP: capabilities.supportsTopP ? input.topP : undefined,
        voice: getSafeSpeechVoice(input.model, input.voice, input.language),
      });
      const providerOperationId = response.headers.get('x-generation-id');
      try {
      const raw = await readBoundedBytes(response, MAX_SPEECH_BYTES - 44, signal);
      const contentType = response.headers.get('content-type') ?? '';
      const pcm = responseFormat === 'pcm' || contentType.toLowerCase().includes('audio/pcm');
      const result: SpeechResult = {
        audioBody: pcm ? wrapSpeechPcmAsWav(raw, Number(contentType.match(/rate=(\d+)/i)?.[1] ?? 24000)) : raw,
        contentType: pcm ? 'audio/wav' : contentType || 'audio/mpeg', generationId: providerOperationId,
      };
      let usage = { ...EMPTY_PROVIDER_USAGE };
      if (providerOperationId) {
        try { usage = (await adapter.getOperationStatus(providerOperationId, { credential: apiKey, signal })).usage; }
        catch { /* Preserve generated bytes; reconciliation fills incomplete usage later. */ }
      }
      return { providerOperationId, result, usage };
      } catch {
        throw new ProviderAdapterError({
          classification: 'ambiguous', code: signal.aborted ? 'canceled' : 'invalid_response',
          httpStatus: signal.aborted ? 499 : 502,
          message: 'Speech was dispatched but its audio could not be read safely. Reconcile before retrying.',
          providerOperationId, retryAfterMs: null,
        });
      }
    },
    transform: (result: SpeechResult) => result,
  };
}
