import { dismissSectionGuide, gotoQaSection } from './release-user-fixture';
import { expect, test } from '@playwright/test';
import sharp from 'sharp';
import { awaitQaAssetIngest, createAudioQaOwner } from './audio-runtime-fixtures';
import { createUuidV7 } from '../src/shared/lib/id';
import { emptySubjectProfile } from '../src/entities/production-graph/model/subject-profile';
import { createDefaultNode } from '../src/entities/production-graph/model/create-default-node';
import { initialProject } from '../src/entities/production-graph/model/initial-project';
import { createEmptyProjectUiState, createProjectExport } from '../src/entities/production-graph/model/project-schema';

test.use({ trace: 'off', video: 'off', screenshot: 'off', viewport: { width: 1440, height: 1000 } });

test('Library projects and one passport across form and Canvas, with access and revision protection', async ({ page, context, baseURL }, testInfo) => {
  test.setTimeout(180_000);
  const origin = new URL(baseURL ?? 'http://localhost:3004');
  if (!['localhost', '127.0.0.1'].includes(origin.hostname)) throw new Error('Local-only QA');
  const owner = await createAudioQaOwner(origin.origin, 'library-organization');
  await context.addCookies(owner.http.browserSessionCookies());
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  let paid = 0;
  await page.route('**/api/ai/**', (route) => { if (route.request().method() === 'GET') return route.continue(); paid++; return route.abort(); });
  const folderUrl = `/api/workspaces/${owner.workspaceId}/folders`;
  const subjectUrl = `/api/workspaces/${owner.workspaceId}/subjects`;
  await gotoQaSection(page, '/folders');
  await page.locator('.production-section-header').getByRole('button', { name: 'Новый проект', exact: true }).click();
  await page.getByRole('textbox', { name: 'Название проекта' }).fill('Content Hub QA');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.locator('.project-folder-card')).toContainText('Content Hub QA');
  const { folders } = await (await owner.http.request(folderUrl)).json();
  const folderId = folders[0].id as string;
  await gotoQaSection(page, '/library');
  await expect(page).toHaveURL(/\/library$/);
  const libraryNavigation = page.getByRole('navigation', { name: 'Разделы Library' });
  for (const name of ['Медиа', 'Персонажи', 'Стили', 'Сохранённые flows', 'По проектам']) {
    await expect(libraryNavigation.getByRole('link', { name, exact: true })).toBeVisible();
  }
  await expect(libraryNavigation.getByRole('link', { name: 'Медиа', exact: true })).toHaveAttribute('aria-current', 'page');
  await libraryNavigation.getByRole('link', { name: 'Персонажи', exact: true }).click();
  await expect(page).toHaveURL(/\/library\?section=subjects$/);
  await expect(libraryNavigation.getByRole('link', { name: 'Персонажи', exact: true })).toHaveAttribute('aria-current', 'page');
  await libraryNavigation.getByRole('link', { name: 'Медиа', exact: true }).click();
  await expect(page).toHaveURL(/\/library$/);

  const create = await owner.http.request('/api/projects', { json: { workspaceId: owner.workspaceId, name: 'Обложка QA' } });
  expect(create.status).toBe(201); const { project } = await create.json();
  const node = createDefaultNode('textPrompt', { x: 0, y: 0 }); node.data = { ...node.data, text: 'Сохранить исходный граф' };
  const snapshot = createProjectExport({ ...initialProject, nodes: [node] }, createEmptyProjectUiState());
  const patch = await owner.http.request(`/api/projects/${project.id}`, { method: 'PATCH', json: { snapshot, expectedRevision: project.revision } });
  expect(patch.status).toBe(200); const before = (await patch.json()).project;
  const image = await sharp({ create: { width: 160, height: 240, channels: 3, background: '#aa8fa1' } }).png().toBuffer();
  const form = new FormData(); form.set('workspaceId', owner.workspaceId); form.set('documentId', project.id); form.set('origin', 'uploaded');
  form.set('file', new Blob([new Uint8Array(image)], { type: 'image/png' }), 'subject-qa.png');
  const upload = await owner.http.request('/api/assets/images', { form });
  const { asset } = await awaitQaAssetIngest(owner.http, upload);
  await gotoQaSection(page, '/flows');
  const card = page.locator('.workspace-project-card').filter({ hasText: 'Обложка QA' });
  await card.getByRole('button', { name: 'More actions: Обложка QA' }).click();
  await page.getByRole('button', { name: 'Переместить в проект', exact: true }).hover();
  await page.getByRole('button', { name: 'Content Hub QA', exact: true }).click();
  await expect.poll(async () => (await (await owner.http.request(`/api/projects/${project.id}`)).json()).project.folderId).toBe(folderId);
  await card.getByRole('button', { name: 'More actions: Обложка QA' }).click();
  await page.getByRole('button', { name: 'Сохранить в библиотеку', exact: true }).click();
  await expect.poll(async () => (await (await owner.http.request(`/api/projects/${project.id}`)).json()).project.librarySaved).toBe(true);
  const after = (await (await owner.http.request(`/api/projects/${project.id}`)).json()).project;
  expect(after.snapshot).toEqual(before.snapshot); expect(after.revision).toBe(before.revision);
  const inFolder = await owner.http.request(`/api/assets?workspaceId=${owner.workspaceId}&folderId=${folderId}`);
  expect((await inFolder.json()).items.map((item: { id: string }) => item.id)).toContain(asset.id);
  await gotoQaSection(page, `/flows?folderId=${folderId}&view=list`);
  await expect(page.locator('.workspace-project-list')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Open Обложка QA' })).toBeVisible();
  await gotoQaSection(page, '/library?section=pipelines');
  await expect(page.getByRole('link', { name: 'Open Обложка QA' })).toBeVisible();
  await page.goto(`/library?folderId=${folderId}`);
  await expect(page.getByRole('heading', { name: 'Library', exact: true })).toBeVisible();
  await expect(page.locator('.library-card')).toHaveCount(1);
  await expect(page.locator('.library-card').getByRole('link')).toHaveAttribute('href', `/library/${asset.id}?folderId=${folderId}`);
  await page.screenshot({ path: testInfo.outputPath('library-folders.png') });

  await gotoQaSection(page, '/library?section=subjects');
  await page.locator('.production-section-header').getByRole('link', { name: 'Создать персонажа', exact: true }).click();
  await page.getByRole('textbox', { name: 'Имя', exact: true }).fill('Лира QA');
  await page.getByRole('textbox', { name: 'Внешность и описание' }).fill('Рыжие волосы, зелёные глаза.');
  await page.getByRole('textbox', { name: 'Неизменные признаки' }).fill('Цвет глаз и форма лица.');
  await page.getByRole('textbox', { name: 'Изменяемые признаки' }).fill('Одежда и эмоции.');
  await page.locator('.studio-subject-form input[type=file]').setInputFiles({ name: 'qa.png', mimeType: 'image/png', buffer: image });
  await expect(page.locator('.studio-reference-grid img')).toHaveCount(1);
  await page.getByRole('button', { name: 'Сохранить персонажа', exact: true }).click();
  await expect(page).toHaveURL(/subject=0/);
  const subjectId = new URL(page.url()).searchParams.get('subject')!;
  await expect(page.getByRole('textbox', { name: 'Имя', exact: true })).toHaveValue('Лира QA');
  await page.reload();
  await expect(page.getByRole('textbox', { name: 'Неизменные признаки' })).toHaveValue('Цвет глаз и форма лица.');
  await page.screenshot({ path: testInfo.outputPath('subject-form.png') });
  await page.getByRole('button', { name: 'Открыть в Subject Builder', exact: true }).click();
  await expect(page).toHaveURL(/\/projects\//);
  await dismissSectionGuide(page, 'canvas');
  const subjectNode = page.locator('.production-node-subjectBuilder');
  await expect(subjectNode.locator('.subject-node-name-input')).toHaveValue('Лира QA');
  await subjectNode.locator('.subject-node-name-input').fill('Лира Canvas QA');
  await subjectNode.getByRole('button', { name: 'Update Library', exact: true }).click();
  await expect(subjectNode).toContainText('Персонаж сохранён в Library');
  const saved = (await (await owner.http.request(`${subjectUrl}/${subjectId}`)).json()).subject;
  expect(saved.name).toBe('Лира Canvas QA'); expect(saved.revision).toBe(2); expect(saved.imageAssetIds).toHaveLength(1);
  await page.goto(`/library?section=subjects&subject=${subjectId}`);
  await expect(page.getByRole('textbox', { name: 'Имя', exact: true })).toHaveValue('Лира Canvas QA');
  await page.setViewportSize({ width: 768, height: 1000 });
  await expect(page.getByRole('button', { name: 'Сохранить персонажа' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('subject-form-tablet.png') });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByRole('button', { name: 'Свернуть меню', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Развернуть меню', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Сохранить персонажа' }).scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('subject-form-phone.png') });

  const fields = { ...emptySubjectProfile, name: 'Версия 3' };
  const outsider = await createAudioQaOwner(origin.origin, 'library-isolation');
  const successes = await Promise.all([0, 1].map(() => owner.http.request(`${subjectUrl}/${subjectId}`, { method: 'PUT', json: { fields, expectedRevision: 2 } })));
  expect(successes.map((response) => response.status).sort()).toEqual([200, 409]);
  expect((await outsider.http.request(subjectUrl)).status).toBe(403);
  expect((await outsider.http.request(`${subjectUrl}/${subjectId}`)).status).toBe(403);
  expect((await outsider.http.request(`${subjectUrl}/${subjectId}`, { method: 'PUT', json: { fields, expectedRevision: 3 } })).status).toBe(403);
  expect((await owner.http.request(`${folderUrl}/${folderId}`, { method: 'PATCH', json: { name: 'Переименован QA' } })).status).toBe(200);
  const foreignFolderResponse = await outsider.http.request(`/api/workspaces/${outsider.workspaceId}/folders`, { json: { name: 'Foreign' } });
  const foreignFolder = (await foreignFolderResponse.json()).folder;
  expect((await owner.http.request(`/api/projects/${project.id}`, { method: 'PATCH', json: { folderId: foreignFolder.id } })).status).toBe(403);
  expect((await outsider.http.request(`/api/assets?workspaceId=${outsider.workspaceId}&folderId=${folderId}`)).status).toBe(200);
  const isolated = await outsider.http.request(`/api/assets?workspaceId=${outsider.workspaceId}&folderId=${folderId}`);
  expect((await isolated.json()).items).toEqual([]);
  expect((await owner.http.request(`${subjectUrl}/${createUuidV7()}`, { method: 'PUT', json: { expectedRevision: 0, fields: { ...fields, imageAssetIds: [createUuidV7()] } } })).status).toBe(422);
  expect((await owner.http.request(`${folderUrl}/${folderId}`, { method: 'DELETE' })).status).toBe(204);
  expect((await (await owner.http.request(`/api/projects/${project.id}`)).json()).project.snapshot).toEqual(before.snapshot);
  expect(paid).toBe(0); expect(errors).toEqual([]);
});
