import { gotoQaSection } from './release-user-fixture';
import { expect, test, type Page } from '@playwright/test';
import { AudioQaHttp, createAudioQaOwner } from './audio-runtime-fixtures';
import { usagePresetPeriod } from '../src/modules/usage/core/usage-periods';
import { buildUsageChart } from '../src/modules/usage/core/usage-chart';
import { usageUiFixtures, removeUsageQaOwner } from './usage-ui-fixtures';

test.use({ trace: 'off', video: 'off' });
test.describe('Workspace Usage', () => {
  test.skip(process.env.USAGE_UI_E2E !== '1', 'Explicit local-only Usage QA opt-in.');
  test('real access; balance, model catalog, averages, chart toggles and tooltip; responsive and Workspace isolation', async ({ page, context, baseURL }, testInfo) => {
    test.setTimeout(240_000);
    expect(['localhost', '127.0.0.1']).toContain(new URL(baseURL!).hostname);
    expect(process.env.USAGE_TEST_DATABASE_URL).toBeTruthy();
    const own = await createAudioQaOwner(baseURL!, 'Usage A');
    let other: Awaited<ReturnType<typeof createAudioQaOwner>> | undefined;
    let release: (() => void) | undefined;
    try {
      other = await createAudioQaOwner(baseURL!, 'Usage B');
      const path = `/api/workspaces/${own.workspaceId}/usage`;
      const response = await own.http.request(path);
      expect(response.status).toBe(200);
      expect(response.headers.get('cache-control')).toBe('private, no-store');
      const initial = await response.json();
      expect(initial.workspaceId).toBe(own.workspaceId);
      expect(initial.rows).toEqual([]);
      expect((await other.http.request(path)).status).toBe(403);
      expect((await own.http.request(`/api/workspaces/${other.workspaceId}/usage`)).status).toBe(403);
      expect((await new AudioQaHttp(baseURL!).request(path)).status).toBe(401);
      expect((await own.http.request(`${path}?from=2026-02-30&to=2026-03-01`)).status).toBe(400);
      expect((await own.http.request(`${path}?timezone=Invalid`)).status).toBe(400);
      await context.addCookies(own.http.browserSessionCookies());
      const errors: string[] = [];
      page.on('pageerror', (error) => errors.push(error.message));
      // Browser-only synthetic money is never inserted in the ledger or sent to a provider.
      const state = await usageUiFixtures(page, own.workspaceId, other.workspaceId);
      await page.setViewportSize({ width: 1440, height: 1100 });
      await gotoQaSection(page, '/usage');
      await expect(page.getByRole('heading', { name: 'Использование', exact: true })).toBeVisible({ timeout: 45_000 });
      const skip = page.locator('.pui-onboarding-card__supplementary').getByRole('button', { name: 'Пропустить онбординг', exact: true });
      if (await skip.isVisible()) await skip.click();
      const stats = page.getByRole('region', { name: 'Общая статистика' });
      const balance = page.getByLabel('Текущий баланс', { exact: true });
      await expect(stats.locator('.usage-metric').first()).toContainText('Баланс');
      await expect(stats.locator('.usage-metric')).toHaveCount(4);
      await expect(balance).toContainText('$42.50');
      await expect(stats).toContainText('≥ $5.10');
      await expect(stats).not.toContainText('Ошибки');
      await expect(page.locator('.usage-line')).toHaveCount(5);
      await expect(page.locator('.usage-legend input')).toHaveCount(0);
      await expect(page.getByText('Данные графика', { exact: true })).toHaveCount(0);
      await expect(page.locator('.usage-chart-detail')).toHaveCount(0);
      const table = page.getByRole('region', { name: 'По моделям', exact: true });
      await expect(table).not.toContainText('openrouter');
      await expect(table.getByRole('row', { name: /Nano Banana/ }).getByRole('cell').last()).toHaveText('$0.25');
      await expect(table.getByRole('row', { name: /GPT 5 Mini/ }).getByRole('cell').last()).toHaveText('$0.0625');
      await expect(table.getByRole('row', { name: /Veo 3.1/ }).getByRole('cell').last()).toContainText('—');
      await expect(table.locator('.usage-model-name .video-model-logo')).toHaveCount(5);
      expect(await page.locator('.usage-card,.usage-type').evaluateAll((elements) => elements.every((el) => getComputedStyle(el).borderTopWidth === '0px'))).toBe(true);
      const tooltip = page.getByRole('tooltip');
      await page.locator('.usage-point-target').last().hover();
      await expect(tooltip).toContainText('≥ $4.85');
      await expect(tooltip).toContainText('18 запросов');
      await expect(tooltip).toHaveCSS('color', 'rgb(255, 255, 255)');
      await page.screenshot({ path: testInfo.outputPath('usage-tooltip.png'), fullPage: true, animations: 'disabled' });
      const videoBadge = page.locator('.usage-legend').getByRole('button', { name: 'Veo 3.1', exact: true });
      await videoBadge.click();
      await expect(videoBadge).toHaveAttribute('aria-pressed', 'false');
      await expect(page.locator('.usage-line')).toHaveCount(4);
      await page.locator('.usage-point-target').last().hover();
      await expect(tooltip).toContainText('$1.85');
      await expect(tooltip).not.toContainText('Veo 3.1');
      await expect(stats).toContainText('≥ $5.10');
      await page.keyboard.press('Escape');
      await expect(tooltip).toHaveCount(0);
      // Keyboard focus exposes the same point details.
      await page.locator('.usage-point-target').first().focus();
      await expect(tooltip).toContainText('$0.25');
      await expect(tooltip).toContainText('2 запросов');
      await page.keyboard.press('Escape');
      await expect(tooltip).toHaveCount(0);
      while (await page.locator('.usage-legend button[aria-pressed=true]').count()) await page.locator('.usage-legend button[aria-pressed=true]').first().click();
      await expect(page.locator('.usage-line')).toHaveCount(0);
      await expect(page.getByRole('status').filter({ hasText: 'Включите модели' })).toBeVisible();
      for (const badge of await page.locator('.usage-legend button').all()) await badge.click();
      await expect(page.locator('.usage-line')).toHaveCount(5);
      await page.getByRole('button', { name: 'Столбчатый график', exact: true }).click();
      await expect(page.locator('.usage-bar').first()).toBeVisible();
      await page.getByRole('button', { name: 'Фильтры', exact: true }).click();
      await select(page, 'Тип операции', 'Видео');
      await expect(stats).toContainText('≥ $3.00');
      await expect(balance).toContainText('$42.50');
      await select(page, 'Тип операции', 'Все типы');
      await select(page, 'Модель', 'GPT 5 Mini');
      await expect(table.getByRole('row')).toHaveCount(2);
      await expect(stats).toContainText('$0.25');
      await select(page, 'Модель', 'Все модели');
      await page.getByRole('button', { name: 'Квартал', exact: true }).click();
      await select(page, 'Детализация', 'По месяцам');
      await expect(page.locator('.usage-point-target')).toHaveCount(buildUsageChart([], usagePresetPeriod('quarter'), 'month').points.length);
      await page.getByRole('button', { name: 'Свой период', exact: true }).click();
      await page.getByLabel('Начало периода', { exact: true }).fill('2026-09-10');
      await page.getByLabel('Конец периода', { exact: true }).fill('2026-09-01');
      await expect(page.getByRole('button', { name: 'Применить', exact: true })).toBeDisabled();
      await expect(page.getByRole('dialog', { name: 'Выбор диапазона дат' }).getByRole('alert')).toBeVisible();
      await page.getByLabel('Начало периода', { exact: true }).fill('2026-08-01');
      await page.getByRole('button', { name: 'Применить', exact: true }).click();
      await expect(page.locator('.usage-point-target')).toHaveCount(2);
      await page.getByRole('button', { name: 'Сегодня', exact: true }).click();
      await expect(page.locator('.usage-point-target')).toHaveCount(1);
      await expect(page.locator('.usage-freshness')).toHaveCount(0);
      await select(page, 'Часовой пояс', 'UTC');
      await select(page, 'Детализация', 'По дням');
      await page.getByRole('button', { name: 'Неделя', exact: true }).click();
      await expect(page.locator('.usage-point-target')).toHaveCount(7);
      await page.getByRole('button', { name: 'Линейный график', exact: true }).click();
      await page.getByRole('button', { name: 'Запросы', exact: true }).click();
      await page.locator('.usage-point-target').last().focus();
      await expect(tooltip).toContainText('≥ $4.85');
      await page.getByRole('button', { name: /^Фильтры/ }).click();
      state.remaining = 40;
      await page.evaluate((workspaceId) => window.dispatchEvent(new CustomEvent('reverie:provider-usage-updated', { detail: { workspaceId } })), own.workspaceId);
      await expect(balance).toContainText('$40.00');
      state.balanceError = true;
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await expect(balance).toContainText('Не обновлён');
      await expect(balance).toContainText('$40.00');
      state.balanceError = false; state.usageError = true;
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await expect(page.locator('.usage-error')).toBeVisible();
      await expect(balance).toContainText('$40.00');
      state.usageError = false; state.remaining = null;
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await expect(balance.locator('strong')).toHaveText('—');
      state.disconnected = true;
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await expect(balance.locator('strong')).toHaveText('$0.00');
      state.disconnected = false; state.remaining = 42.5;
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await expect(balance).toContainText('$42.50');
      await page.getByRole('button', { name: 'Расходы', exact: true }).click();
      await page.screenshot({ path: testInfo.outputPath('usage-desktop.png'), fullPage: true, animations: 'disabled' });
      await table.scrollIntoViewIfNeeded();
      await page.screenshot({ path: testInfo.outputPath('usage-models.png'), fullPage: true, animations: 'disabled' });
      await page.locator('.usage-metrics').scrollIntoViewIfNeeded();
      await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.classList.add('dark'); });
      await page.locator('.usage-point-target').last().hover();
      await page.screenshot({ path: testInfo.outputPath('usage-dark.png'), fullPage: true, animations: 'disabled' });
      await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; document.documentElement.classList.remove('dark'); });
      await page.getByRole('button', { name: 'Свернуть меню' }).click();
      await page.setViewportSize({ width: 390, height: 900 });
      await expect.poll(() => page.locator('.usage-page').evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
      await page.locator('.usage-point-target').first().scrollIntoViewIfNeeded();
      await page.locator('.usage-point-target').first().focus();
      await expect(tooltip).toBeVisible();
      const box = await tooltip.boundingBox();
      expect(box!.x).toBeGreaterThanOrEqual(8); expect(box!.x + box!.width).toBeLessThanOrEqual(382);
      expect(box!.y).toBeGreaterThanOrEqual(8); expect(box!.y + box!.height).toBeLessThanOrEqual(892);
      await page.screenshot({ path: testInfo.outputPath('usage-mobile.png'), fullPage: true, animations: 'disabled' });
      await page.setViewportSize({ width: 1440, height: 1100 });
      state.delayA = true;
      const started = new Promise<void>((resolve) => { state.startedA = resolve; });
      await page.getByRole('button', { name: 'Обновить статистику' }).click();
      await started;
      release = state.releaseA;
      await page.getByRole('button', { name: 'Продукты и рабочие пространства' }).click();
      await select(page, 'Выбрать рабочее пространство', 'Usage QA · Studio B');
      await expect(balance).toContainText('$7.00');
      await expect(page.getByRole('heading', { name: 'За этот период данных нет' })).toBeVisible();
      await expect(page.locator('[data-empty-kind=usage]')).toBeVisible();
      await expect(page.getByRole('button', { name: 'Пополнить баланс', exact: true })).toHaveCount(0);
      release?.();
      await expect(stats).toContainText('$0.00');
      await expect(page.locator('.usage-page')).not.toContainText('Nano Banana');
      await expect(balance).not.toContainText('$42.50');
      expect(errors).toEqual([]);
    } finally {
      release?.();
      await removeUsageQaOwner(own.workspaceId, 'Usage A');
      if (other) await removeUsageQaOwner(other.workspaceId, 'Usage B');
    }
  });
});
async function select(page: Page, label: string, option: string) {
  await page.locator(`[aria-label="${label}"]`).click();
  await page.getByRole('option', { name: option, exact: true }).click();
}
