import assert from 'node:assert/strict';
import { eq } from 'drizzle-orm';
import { getDb, getPostgresPool } from '@/shared/db/client';
import { createUuidV7 } from '@/shared/lib/id';
import { membership } from '@/shared/db/schema/workspace';
import { workerHeartbeat } from '@/shared/db/schema/worker';
import { runtimeClientCredential } from '@/modules/executable-pipelines/adapters/postgres/runtime-schema';
import { pipelineRun, pipelineVersion } from '@/modules/executable-pipelines/adapters/postgres/pipeline-schema';
import { createPostgresPipelineRunStore } from '@/modules/executable-pipelines/adapters/postgres/postgres-pipeline-run-store';
import { createPostgresPipelineRunExecutor } from '@/modules/executable-pipelines/server/postgres-pipeline-run-executor';
import { PipelineWorker } from '@/modules/executable-pipelines/server/pipeline-worker';
import { createRuntimeClient, issueRuntimeCredential, revokeRuntimeCredential, setRuntimeClientEnabled } from '@/modules/executable-pipelines/server/runtime-client-service';
import { authenticateRuntimeClientRequest } from '@/modules/executable-pipelines/server/runtime-client-auth';
import { createRuntimeGrant, repinRuntimeGrant, setRuntimeGrantEnabled } from '@/modules/executable-pipelines/server/runtime-grant-service';
import { getRuntimeGrant, getRuntimeGrantUpdates } from '@/modules/executable-pipelines/server/runtime-grant-read-service';
import { runtimeV2RunSchema } from '@/modules/executable-pipelines/contracts/runtime-v2-run-contracts';
import { runtimeV2Scopes } from '@/modules/executable-pipelines/contracts/runtime-v2-contracts';
import { runRuntimeUsagePersistenceChecks } from '@/modules/executable-pipelines/testing/runtime-usage-smoke';
import { configureRuntimeSmokeDatabase, markRuntimeSmokeWorkerRunning, publishRuntimeSmokeVersion, runtimeSmokeHttp as http, runtimeSmokePin as pin, runtimeSmokeRequest, runtimeSmokeRunBody as runBody, seedRuntimeSmokeActor, seedRuntimeSmokePipeline } from './runtime-v2-smoke-fixtures';
import { runRuntimeProtocolCutoverChecks } from './runtime-v2-smoke-cutover';

configureRuntimeSmokeDatabase();
const facts: string[] = [];
try {
  const owner = await seedRuntimeSmokeActor('Runtime v2 A');
  const otherOwner = await seedRuntimeSmokeActor('Runtime v2 B');
  await markRuntimeSmokeWorkerRunning();
  const client = await createRuntimeClient(owner, { displayName: 'Content Hub smoke', sourceApplication: 'content-hub', externalWorkspaceRef: 'smoke-content-workspace' });
  await assert.rejects(createRuntimeClient(owner, { displayName: 'Duplicate', sourceApplication: 'content-hub', externalWorkspaceRef: 'smoke-content-workspace' }), { code: 'connection_exists' });
  const key = await issueRuntimeCredential(owner, client.id, { label: 'Initial key' });
  const summary = await seedRuntimeSmokePipeline(owner, 'content.summary.smoke');
  const cover = await seedRuntimeSmokePipeline(owner, 'content.caption.smoke');
  const otherPipeline = await seedRuntimeSmokePipeline(otherOwner, 'content.foreign.smoke');
  const grantInput = (pipeline: typeof summary) => ({ pipeline: pipeline.publicId, capabilityKey: pipeline.capabilityKey, ...pin(pipeline.version) });
  let grant = await createRuntimeGrant(owner, client.id, grantInput(summary));
  const secondGrant = await createRuntimeGrant(owner, client.id, grantInput(cover));
  const otherClient = await createRuntimeClient(otherOwner, { displayName: 'Other tenant', sourceApplication: 'content-hub', externalWorkspaceRef: 'other-workspace' });
  const otherKey = await issueRuntimeCredential(otherOwner, otherClient.id, { label: 'Other key' });
  const foreignGrant = await createRuntimeGrant(otherOwner, otherClient.id, grantInput(otherPipeline));
  const token = key.token;
  const catalog = await http(token, 'pipelines');
  assert.equal(catalog.pipelines.length, 2);
  assert.equal(catalog.pipelines.some((item: { publicId: string }) => item.publicId === otherPipeline.publicId), false);
  assert.equal((await http(token, `grants/${foreignGrant.id}`, 'GET', undefined, undefined, 404)).error.code, 'grant_not_found');
  await http(token, `grants/${foreignGrant.id}/runs`, 'POST', runBody(foreignGrant), 'foreign', 404);
  await http(token, `grants/${createUuidV7()}/runs`, 'POST', runBody(grant), 'ungranted', 404);
  await http(token, 'grants', 'POST', grantInput(summary), undefined, 403);
  await assert.rejects(createRuntimeGrant(owner, client.id, grantInput(otherPipeline)), { code: 'pipeline_not_found' });
  await assert.rejects(issueRuntimeCredential(owner, client.id, { label: 'Escalation', scopes: ['pipeline.grants.manage'] }), { code: 'scope_escalation' });
  facts.push('same-Workspace catalog and grants; foreign/ungranted denied; no self-escalation');
  const paid = await seedRuntimeSmokePipeline(owner, 'content.paid-guard.smoke', true);
  const paidGrant = await createRuntimeGrant(owner, client.id, grantInput(paid));
  const deniedPaid = await http(token, `grants/${paidGrant.id}/runs`, 'POST', runBody(paidGrant), 'strict-paid', 422);
  assert.equal(deniedPaid.error.code, 'cost_enforcement_unsupported');
  assert.equal((await getDb().select({ id: pipelineRun.id }).from(pipelineRun)).length, 0);
  facts.push('strict paid pipeline with unknown trusted bound rejected before run/provider dispatch');

  const firstBody = runBody(grant);
  const first = runtimeV2RunSchema.parse(await http(token, `grants/${grant.id}/runs`, 'POST', firstBody, 'first', 202));
  const second = runtimeV2RunSchema.parse(await http(token, `grants/${secondGrant.id}/runs`, 'POST', runBody(secondGrant), 'second', 202));
  assert.notEqual(first.id, second.id);
  assert.equal((await http(token, `grants/${grant.id}/runs`, 'POST', firstBody, 'first', 202)).id, first.id);
  await http(token, `grants/${grant.id}/runs`, 'POST', { ...firstBody, input: { text: 'different' } }, 'first', 409);
  await http(token, `grants/${grant.id}/runs`, 'POST', { ...firstBody, input: {} }, 'invalid-input', 422);
  const queue = createPostgresPipelineRunStore();
  const executor = createPostgresPipelineRunExecutor();
  const worker = new PipelineWorker({ queue, executor });
  assert.equal(await worker.runOnce(), true);
  assert.equal(await worker.runOnce(), true);
  for (const run of [first, second]) {
    const finished = runtimeV2RunSchema.parse(await http(token, `runs/${run.id}`));
    assert.equal(finished.status, 'succeeded');
    assert.deepEqual(finished.outputs, { result: 'v1: runtime smoke' });
    assert.equal(finished.usage.state, 'COMPLETE');
    assert.equal(finished.usage.actualProviderCostUsd, '0.00000000');
    assert.equal(finished.usage.providerCallCount, 0);
  }
  facts.push('one credential -> two grants -> two production deterministic worker runs; exact zero usage');
  const usageRun = await http(token, `grants/${secondGrant.id}/runs`, 'POST', runBody(secondGrant), 'usage-fixture', 202);
  await worker.runOnce();
  const usageEvidence = await runRuntimeUsagePersistenceChecks({ runId: usageRun.id, actorUserId: owner.userId });
  facts.push(`provider usage/reservation persistence: ${JSON.stringify(usageEvidence)}`);
  const cutover = await runRuntimeProtocolCutoverChecks({ actor: owner, pipelineId: cover.pipelineId, publicId: cover.publicId, grant: secondGrant, token });
  while (await worker.runOnce()) { /* Complete both protocol fixtures on the same durable worker. */ }
  assert.equal((await queue.findById(cutover.legacyRunId))?.status, 'succeeded');
  facts.push(`v1/v2 cutover guard: ${JSON.stringify(cutover)}; legacy run completes on v2-capable worker`);

  const v2 = await publishRuntimeSmokeVersion(owner, summary.pipelineId, summary.capabilityKey, 2);
  const update = await getRuntimeGrantUpdates(owner, grant.id);
  assert.equal(update.updateAvailable, true);
  assert.equal(update.pinned.version, 1);
  assert.equal(update.latest.version, 2);
  assert.equal(update.compatibility.structural, 'COMPATIBLE');
  assert.equal(update.compatibility.autoRepinAllowed, false);
  assert.equal((await getRuntimeGrant(owner, grant.id)).pinned.version, 1);
  const candidateGrant = await createRuntimeGrant(owner, client.id, { ...grantInput(summary), ...pin(v2) });
  const candidate = await http(token, `grants/${candidateGrant.id}/runs`, 'POST', runBody(candidateGrant), 'candidate', 202);
  await worker.runOnce();
  assert.equal((await http(token, `runs/${candidate.id}`)).outputs.result, 'v2: runtime smoke');
  assert.equal((await getRuntimeGrant(owner, grant.id)).pinned.version, 1);
  const inflightBody = runBody(grant, 'in-flight');
  const inflight = await http(token, `grants/${grant.id}/runs`, 'POST', inflightBody, 'inflight', 202);
  let started!: () => void; let release!: () => void;
  const startedPromise = new Promise<void>((resolve) => { started = resolve; });
  const releasePromise = new Promise<void>((resolve) => { release = resolve; });
  const waitingWorker = new PipelineWorker({ queue, executor: { async execute(input) { started(); await releasePromise; return executor.execute(input); } } });
  const completion = waitingWorker.runOnce();
  await startedPromise;
  try {
    const concurrent = await Promise.allSettled([1, 2].map(() => repinRuntimeGrant(owner, grant.id, { expectedGrantRevision: grant.revision, ...pin(v2) })));
    assert.equal(concurrent.filter((result) => result.status === 'fulfilled').length, 1);
    assert.equal(concurrent.filter((result) => result.status === 'rejected' && result.reason.code === 'stale_grant_revision').length, 1);
    grant = await getRuntimeGrant(owner, grant.id);
    assert.equal(grant.pinned.version, 2);
    const replay = await http(token, `grants/${grant.id}/runs`, 'POST', inflightBody, 'inflight', 202);
    assert.equal(replay.id, inflight.id);
    assert.equal(replay.pipeline.version, 1);
  } finally { release(); await completion; }
  assert.equal((await http(token, `runs/${inflight.id}`)).outputs.result, 'v1: in-flight');
  grant = await repinRuntimeGrant(owner, grant.id, { expectedGrantRevision: grant.revision, ...pin(summary.version) }, true);
  assert.equal(grant.pinned.version, 1);
  const rollbackUpdate = await getRuntimeGrantUpdates(owner, grant.id);
  assert.ok(rollbackUpdate.rollbackVersions.some((version) => version.version === 2));
  const breaking = await publishRuntimeSmokeVersion(owner, summary.pipelineId, summary.capabilityKey, 3, true);
  await assert.rejects(repinRuntimeGrant(owner, grant.id, { expectedGrantRevision: grant.revision, ...pin(breaking) }), { code: 'incompatible_repin' });
  facts.push('publish -> update available -> candidate test -> CAS repin -> pinned in-flight completion -> rollback; breaking denied');

  const rotated = await issueRuntimeCredential(owner, client.id, { label: 'Rotation overlap' });
  await http(token, 'client'); await http(rotated.token, 'client');
  await assert.rejects(issueRuntimeCredential(owner, client.id, { label: 'Third key' }), { code: 'rotation_overlap_limit' });
  await revokeRuntimeCredential(owner, client.id, key.credential.id);
  assert.equal((await http(token, 'client', 'GET', undefined, undefined, 401)).error.code, 'revoked_credential');
  assert.equal((await http(rotated.token, `runs/${first.id}`)).id, first.id);
  assert.equal((await http(otherKey.token, `runs/${first.id}`, 'GET', undefined, undefined, 404)).error.code, 'run_not_found');
  await http(otherKey.token, `runs/${first.id}/cancel`, 'POST', {}, undefined, 404);
  await http(otherKey.token, `runs/${first.id}/artifacts/${createUuidV7()}`, 'GET', undefined, undefined, 404);
  await http(rotated.token, `runs/${first.id}/artifacts/${createUuidV7()}`, 'GET', undefined, undefined, 404);
  await http(rotated.token, `runs/${first.id}/cancel`, 'POST', {}, undefined, 409);
  facts.push('rotation overlap/revoke; new key reads old run; foreign read/cancel/artifact denied');

  const canceled = await http(rotated.token, `grants/${grant.id}/runs`, 'POST', runBody(grant), 'cancel', 202);
  assert.equal((await http(rotated.token, `runs/${canceled.id}/cancel`, 'POST', {})).status, 'canceled');
  await setRuntimeGrantEnabled(owner, grant.id, false, grant.revision);
  await http(rotated.token, `grants/${grant.id}/runs`, 'POST', runBody(grant), 'disabled-grant', 403);
  assert.equal((await http(rotated.token, `runs/${first.id}`)).id, first.id);
  await setRuntimeClientEnabled(owner, client.id, false);
  await http(rotated.token, 'client', 'GET', undefined, undefined, 403);
  await setRuntimeClientEnabled(owner, client.id, true);
  await getDb().update(runtimeClientCredential).set({ expiresAt: new Date(0) }).where(eq(runtimeClientCredential.id, rotated.credential.id));
  assert.equal((await http(rotated.token, 'client', 'GET', undefined, undefined, 401)).error.code, 'expired_credential');
  const readOnly = await issueRuntimeCredential(owner, client.id, { label: 'Read-only', scopes: ['pipeline.run.read'] });
  await http(readOnly.token, `grants/${secondGrant.id}/runs`, 'POST', runBody(secondGrant), 'scope-denied', 403);
  await http(readOnly.token, 'pipelines', 'GET', undefined, undefined, 403);
  const beforeCount = (await getDb().select({ id: pipelineRun.id }).from(pipelineRun)).length;
  await getDb().update(workerHeartbeat).set({ status: 'stopped' }).where(eq(workerHeartbeat.workerName, 'pipeline'));
  await http(otherKey.token, `grants/${foreignGrant.id}/runs`, 'POST', runBody(foreignGrant), 'no-worker', 503);
  assert.equal((await getDb().select({ id: pipelineRun.id }).from(pipelineRun)).length, beforeCount);
  await markRuntimeSmokeWorkerRunning();
  await getDb().update(pipelineVersion).set({ checksum: 'f'.repeat(64) }).where(eq(pipelineVersion.id, otherPipeline.version.id));
  await http(otherKey.token, `grants/${foreignGrant.id}/runs`, 'POST', runBody(foreignGrant), 'mismatch', 409);
  await getDb().update(membership).set({ role: 'member' }).where(eq(membership.workspaceId, owner.workspaceId));
  await assert.rejects(createRuntimeClient(owner, { displayName: 'Denied member', sourceApplication: 'other', externalWorkspaceRef: 'denied' }), { code: 'missing_scope' });
  const manager = await createRuntimeClient(otherOwner, { displayName: 'Explicit grant manager', sourceApplication: 'manager', externalWorkspaceRef: 'manager', scopes: [...runtimeV2Scopes] });
  const managerKey = await issueRuntimeCredential(otherOwner, manager.id, { label: 'Manager' });
  const managerActor = await authenticateRuntimeClientRequest(runtimeSmokeRequest(managerKey.token, 'client'));
  await assert.rejects(createRuntimeGrant(managerActor, manager.id, grantInput(summary)), { code: 'pipeline_not_found' });
  facts.push('queued cancellation retained; disabled/expired/client/scope checks; worker/checksum guards before dispatch; member cannot manage');
  console.log(JSON.stringify({ status: 'passed', facts, runIds: [first.id, second.id, candidate.id, inflight.id, canceled.id], workspaceIds: [owner.workspaceId, otherOwner.workspaceId] }, null, 2));
} finally {
  await getPostgresPool().end();
}
