export const COMPOSITION_TEXT_FONT_SIZE_MIN = 8;
export const COMPOSITION_TEXT_FONT_SIZE_MAX = 240;
export const COMPOSITION_TEXT_LINE_HEIGHT_MIN = 1;
export const COMPOSITION_TEXT_LINE_HEIGHT_MAX = 600;
