import type { ProductionNodeDefinitionMap } from './node-registry-types';

export const textNodeDefinitions = {
  textPrompt: {
    type: 'textPrompt',
    title: 'Prompt',
    menuLabel: 'Text prompt',
    collapsible: true,
    defaultHeight: 370,
    ports: [{ id: 'text', label: 'Text', kind: 'text', side: 'output' }],
    createData: () => ({
      title: 'Prompt',
      disabledResultFilterIds: [],
      result: '',
      sourceCount: 0,
      text: '',
      textareaHeight: 248,
      variableDisplayMode: 'source-value',
      variables: [],
    }),
  },
  textConcat: {
    type: 'textConcat',
    title: 'Concat',
    menuLabel: 'Text concat',
    collapsible: true,
    defaultHeight: 637,
    ports: [
      { id: 'text-0', label: 'Input 1', kind: 'text', side: 'input' },
      { id: 'text-1', label: 'Input 2', kind: 'text', side: 'input' },
      { id: 'result', label: 'Result', kind: 'text', side: 'output' },
    ],
    createData: () => ({
      title: 'Concat',
      separator: 'double-newline',
      customSeparator: '',
      disabledResultFilterIds: [],
      inputCount: 2,
      prefix: '',
      optionalTextHeight: 95,
      suffix: '',
      result: '',
      sourceCount: 0,
    }),
  },
  textGeneration: {
    type: 'textGeneration',
    title: 'Text Gen',
    menuLabel: 'Text generation',
    collapsible: true,
    defaultHeight: 757,
    ports: [
      { id: 'text', label: 'Prompt', kind: 'text', side: 'input' },
      { id: 'result', label: 'Result', kind: 'text', side: 'output' },
    ],
    createData: () => ({
      title: 'Text Gen',
      model: 'google/gemini-2.5-flash',
      instruction: 'Rewrite the connected text into a concise production-ready image prompt.',
      outputStyle: 'plain',
      reasoning: 'low',
      temperature: 1,
      activeResultIndex: -1,
      disabledResultFilterIds: [],
      result: '',
      resultTexts: [],
    }),
  },
  textFormatter: {
    type: 'textFormatter',
    title: 'Formatter',
    menuLabel: 'Formatter',
    collapsible: true,
    defaultHeight: 520,
    ports: [
      { id: 'text', label: 'Text', kind: 'text', side: 'input' },
      { id: 'result', label: 'Formatted', kind: 'text', side: 'output' },
    ],
    createData: () => ({
      title: 'Formatter',
      editorHeight: 360,
      plainText: '',
      presetId: 'telegram-post',
      result: '',
      richText: '',
      sourceCount: 0,
      sourceText: '',
    }),
  },
  textSplitter: {
    type: 'textSplitter',
    title: 'Splitter',
    menuLabel: 'Text splitter',
    collapsible: true,
    defaultHeight: 422,
    ports: [
      { id: 'text', label: 'Text', kind: 'text', side: 'input' },
      { id: 'items', label: 'Items', kind: 'text', side: 'output' },
      { id: 'item-0', label: 'Item 1', kind: 'text', side: 'output' },
    ],
    createData: () => ({
      title: 'Splitter',
      mode: 'delimiter',
      delimiter: '*',
      activeItemIndex: 0,
      items: [],
      result: '',
      sourceText: '',
    }),
  },
} satisfies ProductionNodeDefinitionMap<'textPrompt' | 'textConcat' | 'textGeneration' | 'textFormatter' | 'textSplitter'>;
