import type { GraphPort, ProductionNodeType } from './types';
import { NODE_DEFINITIONS } from './node-registry';

export const NODE_PORTS: Record<ProductionNodeType, GraphPort[]> = {
  importImage: NODE_DEFINITIONS.importImage.ports,
  textPrompt: NODE_DEFINITIONS.textPrompt.ports,
  textConcat: NODE_DEFINITIONS.textConcat.ports,
  textGeneration: NODE_DEFINITIONS.textGeneration.ports,
  textToSpeech: NODE_DEFINITIONS.textToSpeech.ports,
  speechToText: NODE_DEFINITIONS.speechToText.ports,
  audioConvert: NODE_DEFINITIONS.audioConvert.ports,
  timelineHandoff: NODE_DEFINITIONS.timelineHandoff.ports,
  reverieStories: NODE_DEFINITIONS.reverieStories.ports,
  generateVideo: NODE_DEFINITIONS.generateVideo.ports,
  textFormatter: NODE_DEFINITIONS.textFormatter.ports,
  textSplitter: NODE_DEFINITIONS.textSplitter.ports,
  pipelineInput: NODE_DEFINITIONS.pipelineInput.ports,
  pipelineOutput: NODE_DEFINITIONS.pipelineOutput.ports,
  structuredOutput: NODE_DEFINITIONS.structuredOutput.ports,
  router: NODE_DEFINITIONS.router.ports,
  iterator: NODE_DEFINITIONS.iterator.ports,
  subjectBuilder: NODE_DEFINITIONS.subjectBuilder.ports,
  locationBuilder: NODE_DEFINITIONS.locationBuilder.ports,
  telegramPublication: NODE_DEFINITIONS.telegramPublication.ports,
  imageToText: NODE_DEFINITIONS.imageToText.ports,
  qrCode: NODE_DEFINITIONS.qrCode.ports,
  referenceComposer: NODE_DEFINITIONS.referenceComposer.ports,
  composition: NODE_DEFINITIONS.composition.ports,
  generateImage: NODE_DEFINITIONS.generateImage.ports,
  sketch: NODE_DEFINITIONS.sketch.ports,
  cropImage: NODE_DEFINITIONS.cropImage.ports,
  adjustment: NODE_DEFINITIONS.adjustment.ports,
  curves: NODE_DEFINITIONS.curves.ports,
  frequencyRetouch: NODE_DEFINITIONS.frequencyRetouch.ports,
  refineImage: NODE_DEFINITIONS.refineImage.ports,
  removeBackground: NODE_DEFINITIONS.removeBackground.ports,
  exportImage: NODE_DEFINITIONS.exportImage.ports,
  banner: NODE_DEFINITIONS.banner.ports,
  preview: NODE_DEFINITIONS.preview.ports,
};
